runtime: nodejs10
env: standard

service: default

env_variables:
  NODEENV: production
  TZ: Asia/Tokyo

instance_class: F1

automatic_scaling:
  max_instances: 1
  max_idle_instances: 1
  min_idle_instances: automatic
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

  - url: /.*
    script: auto
    secure: always
