version: '3'

services:
  app:
    container_name: sample-project-ts-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL:db://postgres:postgres@postgres:5432/db
      - NODE_ENV=development
      # - MONGO_DATABASE=mongodb://mongodb/myapp
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 8081:8080
    tty: true
    links:
      - db
  db:
    image: postgres:alpine
    container_name: test-db
    tty: true
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      POSTGRES_DB: db
    ports:
      - '5434:5432'
